#!/bin/bash
# Auto-commit generated skills to git
# Called by PostToolUse hook after skill generation

SKILL_DIR="$1"

# Exit if no argument provided
if [ -z "$SKILL_DIR" ]; then
    echo "Usage: auto-commit.sh <skill-directory>"
    exit 1
fi

# Check if directory exists
if [ ! -d "$SKILL_DIR" ]; then
    echo "Directory not found: $SKILL_DIR"
    exit 1
fi

# Get the parent directory
PARENT_DIR=$(dirname "$SKILL_DIR")

# Check if we're in a git repository
cd "$PARENT_DIR" || exit 1

if [ -d ".git" ] || git rev-parse --git-dir > /dev/null 2>&1; then
    TOPIC=$(basename "$SKILL_DIR")

    # Stage the skill directory
    git add "$SKILL_DIR"

    # Check if there are changes to commit
    if git diff --cached --quiet; then
        echo "No changes to commit for $TOPIC"
        exit 0
    fi

    # Commit with descriptive message
    git commit -m "feat: add skill for $TOPIC

Generated by claude-self-learning plugin.
"

    echo "Committed skill for $TOPIC"
else
    echo "Not a git repository, skipping auto-commit"
fi
