#!/bin/bash
# Generate a skill using Tavily - helper script for testing
# Usage: ./scripts/generate-skill.sh <topic> [output-dir]

set -e

TOPIC="$1"
OUTPUT_DIR="${2:-./storage/skills}"

if [ -z "$TOPIC" ]; then
    echo "Usage: generate-skill.sh <topic> [output-dir]"
    echo "Example: generate-skill.sh 'anthropic api'"
    exit 1
fi

# Slugify topic
SLUG=$(echo "$TOPIC" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')

SKILL_DIR="$OUTPUT_DIR/$SLUG"
mkdir -p "$SKILL_DIR"

echo "Generating skill for: $TOPIC"
echo "Output directory: $SKILL_DIR"
echo ""

# Check Tavily availability
TAVILY_SEARCH="$HOME/.agents/skills/search/scripts/search.sh"
if [ ! -f "$TAVILY_SEARCH" ]; then
    echo "Error: Tavily search script not found at $TAVILY_SEARCH"
    exit 1
fi

# Search for documentation
echo "Searching for official documentation..."
SEARCH_RESULT=$("$TAVILY_SEARCH" "{\"query\": \"official $TOPIC documentation\", \"max_results\": 5, \"search_depth\": \"advanced\"}" 2>&1) || true

if [ -z "$SEARCH_RESULT" ]; then
    echo "Warning: No search results returned"
fi

# Create metadata
META_FILE="$SKILL_DIR/.meta.json"
cat > "$META_FILE" << EOF
{
  "created": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "updated": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "topic": "$TOPIC",
  "slug": "$SLUG",
  "version": "1.0.0",
  "sources": [],
  "generator": "claude-self-learning"
}
EOF

echo "Created metadata: $META_FILE"

# Create placeholder skill
SKILL_FILE="$SKILL_DIR/SKILL.md"
cat > "$SKILL_FILE" << EOF
---
name: $SLUG
description: [Generated skill for $TOPIC - needs completion]
version: 1.0.0
sources_verified: $(date +%Y-%m-%d)
---

# $TOPIC

[This is a placeholder skill. Complete the research and fill in the sections below.]

## Quick Reference

| Item | Value |
|------|-------|
| Official Docs | [TODO] |
| Installation | [TODO] |
| Auth Required | [TODO] |

## Installation

### Python

\`\`\`bash
# TODO: Add Python installation
\`\`\`

### TypeScript

\`\`\`bash
# TODO: Add TypeScript installation
\`\`\`

## Basic Usage

[TODO: Add usage examples]

## Best Practices

1. [TODO]

## Common Errors

| Error | Cause | Fix |
|-------|-------|-----|
| [TODO] | [TODO] | [TODO] |

---
*Skill generated by claude-self-learning on $(date +%Y-%m-%d)*
*Requires completion*
EOF

echo "Created skill placeholder: $SKILL_FILE"
echo ""
echo "Next steps:"
echo "1. Use Claude with /learn $TOPIC to complete the skill"
echo "2. Or manually fill in the TODO sections"
echo ""
echo "Done!"
